fix(dmd/generic): Fix the dmd runnable_cxx parts of the checkPhase by using GCC11
The recent upgrade of Nixpkgs caused stdenv.cc to be upgraded from GCC11 to
GCC12, which seems to not work with DMD's `extern(C++)` test suite. What happens
is that the when GCC12 is used the `runnable_cxx/cppb.cpp.o` object file is
missing symbols:

```
export SHELL=/nix/store/zlf0f88vj30sc7567b80l52d19pbdmy2-bash-5.2-p15/bin/bash
export HOST_DMD=/nix/store/ps0lnm6z57fnghch009mkgic8k3shb3x-dmd-binary-2.098.0/bin/dmd
export CC=/nix/store/nlgyw2fv0cm8rkz8qm1jyw78vyif1bl9-gcc-wrapper-12.2.0/bin/cc
export NIX_HARDENING_ENABLE=''
export NIX_ENFORCE_PURITY=''
export MAKE=/nix/store/18gs8jn6ss6gg48r49gapplbyq3j6qny-gnumake-4.4.1/bin/make

$MAKE -C $DLANG/dmd -f posix.mak
(cd $DLANG/dmd/test && $HOST_DMD -i -run ./run.d -e runnable_cxx/cppa.d)
```

Which fails with:

```
Test 'runnable_cxx/cppa.d' failed. The logged output:
/nix/store/nlgyw2fv0cm8rkz8qm1jyw78vyif1bl9-gcc-wrapper-12.2.0/bin/cc \
  -m64 -c runnable_cxx/extra-files/cppb.cpp \
  -o $DLANG/dmd/test/test_results/runnable_cxx/cppb.cpp.o \
  -std=c++11

$DLANG/dmd/generated/linux/release/64/dmd -conf= -m64 \
  -Irunnable_cxx -checkaction=C  -fPIC -L-lstdc++ -L--no-demangle \
  -od$DLANG/dmd/test/test_results/runnable_cxx \
  -of$DLANG/dmd/test/test_results/runnable_cxx/cppa_0 \
  runnable_cxx/cppa.d \
  $DLANG/dmd/test/test_results/runnable_cxx/cppb.cpp.o

/nix/store/f4qnwzv6y0nq8lix33jr5ykkyybs6fxf-binutils-2.40/bin/ld:
$DLANG/dmd/test/test_results/runnable_cxx/cppa_0.o: in function
`_ZNSaIiE10deallocateEPim':
runnable_cxx/cppa.d:(.text._ZNSaIiE10deallocateEPim[_ZNSaIiE10deallocateEPim]+0x5):
undefined reference to `_ZN9__gnu_cxx13new_allocatorIiE10deallocateEPim'
```

Essentially saying that in the function
`std::allocator<int>::deallocate(int*, unsigned long)` the linker was a
reference to `__gnu_cxx::new_allocator<int>::deallocate(int*, unsigned long)`
which was not found.

Since further investigation is needed and the goal is to fix the CI build, we
will explicitly set the `CC` env variable to the point to the GCC11 binary,
which appears to work without issues.